---

- name: Install
  when: package_state == 'present'
  ansible.builtin.include_tasks: install.yml

- name: Uninstall
  when: package_state == 'absent'
  ansible.builtin.include_tasks: uninstall.yml
