---

- name: "{{ package_mode }} | packages"
  become: true
  when:
    - not ansible_check_mode
    - package_state == 'present'
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ package_packages }}"

- name: "{{ package_mode }} | dnf autoremove"
  become: true
  when:
    - not ansible_check_mode
    - package_state == 'absent'
  ansible.builtin.command: dnf autoremove -y

- name: "{{ package_mode }} | dnf clean"
  become: true
  when:
    - not ansible_check_mode
    - package_state == 'absent'
  ansible.builtin.command: dnf clean -y
