---

- name: "{{ package_mode }} | packages"
  become: true
  when:
    - not ansible_check_mode
  ansible.builtin.package:
    name: "{{ item.package }}"
    state: "{{ 'absent' if item.force_remove is defined and item.force_remove else 'present' }}"
  loop: "{{ package_packages }}"
  loop_control:
    label: "{{ item.package }}"
